# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

vars:
  GREETING: Hello, world!
  USERNAME:
    sh: whoami
  HOSTNAME:
    sh: hostname

tasks:
  default:
    desc: List all tasks
    cmds:
      - task -l
    silent: true

  help:
    desc: Apply Nix configuration
    cmds:
      - glow README.md

  docs:
    desc: Show maelstrom documentation
    cmds:
      - glow {{.MAELSTROM_DOCS}}

  echo:
    desc: Run the echo challenge
    cmds:
      - go install cmd/echo/*
      - maelstrom test -w echo --bin $GOPATH/bin/echo --node-count 1 --time-limit 10

  unique-ids:
    desc: Run the unique-ids challenge
    cmds:
      - go install  unique-ids/*
      - maelstrom test -w unique-ids --bin $GOPATH/bin/unique-ids --time-limit 30 --rate 1000 --node-count 3 --availability total --nemesis partition

  broadcast-single-node:
    desc: Run the broadcast-single-node challenge
    cmds:
      - go install  broadcast-single-node/*
      - maelstrom test -w broadcast --bin $GOPATH/bin/maelstrom-broadcast --node-count 1 --time-limit 20 --rate 10

  broadcast-multi-node:
    desc: Run the broadcast-multi-node challenge
    cmds:
      - go install broadcast-multi-node/*
      - maelstrom test -w broadcast --bin $GOPATH/bin/maelstrom-broadcast-multi --node-count 5 --time-limit 20 --rate 10

  broadcast-fault-tolerant:
    desc: Run the broadcast-fault-tolerant challenge
    cmds:
      - go install broadcast-fault-tolerant/*
      - maelstrom test -w broadcast --bin $GOPATH/bin/maelstrom-fault-tolerant --node-count 5 --time-limit 20 --rate 10 --nemesis partition

  broadcast-efficient:
    desc: Run the broadcast-efficient challenge
    cmds:
      - go install cmd/broadcast-efficient/*
      - maelstrom test -w broadcast --bin $GOPATH/bin/broadcast-efficient-1 --node-count 25 --time-limit 20 --rate 100 --latency 100

  grow-only-counter:
    desc: Run the grow-only-counter challenge
    cmds:
      - go install grow-only-counter/*
      - maelstrom test -w g-counter --bin $GOPATH/bin/grow-only-counter --node-count 3 --rate 100 --time-limit 20 --nemesis partition
